name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  your-job-name:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # MUST BE AT JOB LEVEL OR WORKFLOW LEVEL
      contents: read
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
